# Generated by Django 4.2.11 on 2024-03-11 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_citi_alter_user_phone_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежы'},
        ),
    ]
