# Generated by Django 4.2.11 on 2024-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_lesson',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID цены'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID банковского продукта'),
        ),
    ]
