version: '3'

services:
  app:
    build: .
    tty: true
    command:
      - bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - '6379:6379'
  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app