# Generated by Django 4.2.11 on 2024-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(upload_to='course/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(upload_to='lesson/', verbose_name='Превью'),
        ),
    ]
