# Generated by Django 4.2.11 on 2024-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Подписан пользователь'),
        ),
    ]
